#!/usr/bin/env python3
import sys
import os

class IndexedMinHeap:
    def __init__(self, max_nodes):
        self.heap = [] # stores (distance, node)
        self.pos = [-1] * (max_nodes + 1)
        self.size = 0

    def push(self, dist, node):
        self.heap.append((dist, node))
        self.pos[node] = self.size
        self._sift_up(self.size)
        self.size += 1

    def pop(self):
        if self.size == 0:
            return None
        min_dist, min_node = self.heap[0]
        self.pos[min_node] = -1
        
        last_item = self.heap.pop()
        self.size -= 1
        
        if self.size > 0:
            self.heap[0] = last_item
            self.pos[last_item[1]] = 0
            self._sift_down(0)
            
        return min_dist, min_node

    def decrease_key(self, dist, node):
        idx = self.pos[node]
        if idx == -1:
            self.push(dist, node)
        elif dist < self.heap[idx][0]:
            self.heap[idx] = (dist, node)
            self._sift_up(idx)
            
    def _sift_up(self, idx):
        item = self.heap[idx]
        dist, node = item
        while idx > 0:
            parent = (idx - 1) >> 2
            p_item = self.heap[parent]
            if dist < p_item[0]:
                self.heap[idx] = p_item
                self.pos[p_item[1]] = idx
                idx = parent
            else:
                break
        self.heap[idx] = item
        self.pos[node] = idx
                
    def _sift_down(self, idx):
        size = self.size
        item = self.heap[idx]
        dist, node = item
        
        while True:
            child1 = (idx << 2) + 1
            if child1 >= size:
                break
            
            smallest_child = child1
            min_dist = self.heap[child1][0]
            
            child2 = child1 + 1
            if child2 < size:
                d2 = self.heap[child2][0]
                if d2 < min_dist:
                    min_dist = d2
                    smallest_child = child2
                    
                child3 = child1 + 2
                if child3 < size:
                    d3 = self.heap[child3][0]
                    if d3 < min_dist:
                        min_dist = d3
                        smallest_child = child3
                        
                    child4 = child1 + 3
                    if child4 < size:
                        d4 = self.heap[child4][0]
                        if d4 < min_dist:
                            min_dist = d4
                            smallest_child = child4
            
            if min_dist < dist:
                c_item = self.heap[smallest_child]
                self.heap[idx] = c_item
                self.pos[c_item[1]] = idx
                idx = smallest_child
            else:
                break
                
        self.heap[idx] = item
        self.pos[node] = idx

def main():
    if len(sys.argv) < 2:
        print("Usage: solve <input_file>")
        sys.exit(1)

    filename = sys.argv[1]

    # Use centralized dimacs loader which has binary caching
    sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    import dimacs

    try:
        num_nodes, edges = dimacs.load_dimacs(filename)
    except ValueError as e:
        print(f"Error: {e}")
        sys.exit(1)

    num_edges = edges.shape[0]

    head = [-1] * (num_nodes + 1)
    to = [0] * num_edges
    weight = [0] * num_edges
    nxt = [0] * num_edges
    
    for i, (u, v, w) in enumerate(edges.tolist()):
        u = int(u)
        v = int(v)
        to[i] = v
        weight[i] = w
        nxt[i] = head[u]
        head[u] = i

    dist = [float('inf')] * (num_nodes + 1)
    dist[1] = 0
    
    pq = IndexedMinHeap(num_nodes)
    pq.push(0, 1)
    
    while pq.size > 0:
        d, u = pq.pop()
        
        if u == num_nodes:
            print(d)
            return
            
        e = head[u]
        while e != -1:
            v = to[e]
            w = weight[e]
            if dist[u] + w < dist[v]:
                dist[v] = dist[u] + w
                pq.decrease_key(dist[v], v)
            e = nxt[e]
            
    print("Unreachable")

if __name__ == '__main__':
    main()
