#!/usr/bin/env python3
import sys
import os

class IndexedMinHeap:
    def __init__(self, max_nodes):
        self.heap = [] # stores (distance, node)
        self.pos = [-1] * (max_nodes + 1)
        self.size = 0

    def push(self, dist, node):
        self.heap.append((dist, node))
        self.pos[node] = self.size
        self._sift_up(self.size)
        self.size += 1

    def pop(self):
        if self.size == 0:
            return None
        min_dist, min_node = self.heap[0]
        self.pos[min_node] = -1
        
        last_dist, last_node = self.heap.pop()
        self.size -= 1
        
        if self.size > 0:
            self.heap[0] = (last_dist, last_node)
            self.pos[last_node] = 0
            self._sift_down(0)
            
        return min_dist, min_node

    def decrease_key(self, dist, node):
        idx = self.pos[node]
        if idx == -1:
            self.push(dist, node)
        elif dist < self.heap[idx][0]:
            self.heap[idx] = (dist, node)
            self._sift_up(idx)
            
    def _sift_up(self, idx):
        while idx > 0:
            parent = (idx - 1) >> 1
            if self.heap[idx][0] < self.heap[parent][0]:
                self._swap(idx, parent)
                idx = parent
            else:
                break
                
    def _sift_down(self, idx):
        while True:
            left = (idx << 1) + 1
            right = left + 1
            smallest = idx
            
            if left < self.size and self.heap[left][0] < self.heap[smallest][0]:
                smallest = left
            if right < self.size and self.heap[right][0] < self.heap[smallest][0]:
                smallest = right
                
            if smallest != idx:
                self._swap(idx, smallest)
                idx = smallest
            else:
                break
                
    def _swap(self, i, j):
        self.heap[i], self.heap[j] = self.heap[j], self.heap[i]
        self.pos[self.heap[i][1]] = i
        self.pos[self.heap[j][1]] = j

def main():
    if len(sys.argv) < 2:
        print("Usage: solve <input_file>")
        sys.exit(1)

    filename = sys.argv[1]

    # Use centralized dimacs loader which has binary caching
    sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    import dimacs

    try:
        num_nodes, edges = dimacs.load_dimacs(filename)
    except ValueError as e:
        print(f"Error: {e}")
        sys.exit(1)

    num_edges = edges.shape[0]

    head = [-1] * (num_nodes + 1)
    to = [0] * num_edges
    weight = [0] * num_edges
    nxt = [0] * num_edges
    
    for i, (u, v, w) in enumerate(edges.tolist()):
        u = int(u)
        v = int(v)
        to[i] = v
        weight[i] = w
        nxt[i] = head[u]
        head[u] = i

    dist = [float('inf')] * (num_nodes + 1)
    dist[1] = 0
    
    pq = IndexedMinHeap(num_nodes)
    pq.push(0, 1)
    
    while pq.size > 0:
        d, u = pq.pop()
        
        if u == num_nodes:
            print(d)
            return
            
        e = head[u]
        while e != -1:
            v = to[e]
            w = weight[e]
            if dist[u] + w < dist[v]:
                dist[v] = dist[u] + w
                pq.decrease_key(dist[v], v)
            e = nxt[e]
            
    print("Unreachable")

if __name__ == '__main__':
    main()
