#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
if [ ! -f "$DIR/target/release/bellman_ford" ]; then
    (cd "$DIR" && cargo build --release -q)
fi
"$DIR/target/release/bellman_ford" "$@"
